#!/usr/bin/env bash
#
# pomodate
#   convenience commands for use in he shell which help working with pomoutils
#
# install:
#   for l in \
#       thisweek lastweek \
#       thismonth lastmonth \
#       yesterday tomorrow today \
#       now \
#   ; do
#       ln -s pomodate $l
#   done
#
# todo:
#   - maybe all the dates output should be iso? not just thisweek/lastweek
#
# scott@smemsh.net
# http://smemsh.net/src/pomoutils/
# http://spdx.org/licenses/GPL-2.0
#
##############################################################################

invname=${0##*/}

mflags=%Y%m
dflags=%Y%m%d
wflags=%G%V
nflags=%Y%m%d%H%M%S

pomo_thisweek  () { date +$wflags; }
pomo_thismonth () { date +$mflags; }
pomo_today     () { date +$dflags; }
pomo_now       () { date +$nflags; }

pomo_lastweek  () { date -d last-week +$wflags; }
pomo_lastmonth () { date -d last-month +$mflags; }
pomo_yesterday () { date -d yesterday +$dflags; }
pomo_tomorrow  () { date -d tomorrow +$dflags; }

main ()
{
	if [[ $(declare -F pomo_$invname) ]]; then
		pomo_$invname "$@"
	else
		compgen -A function _
		exit 1
	fi
}

main "$@"
